version: '3.8'

services:
  socket-server:
    build: ./server
    ports:
      - "9999:9999"
    networks:
      - socket-network

  socket-client:
    build: ./client
    depends_on:
      - socket-server
    networks:
      - socket-network

networks:
  socket-network:
    driver: bridge
